# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/simoncui/proj/epark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/simoncui/proj/epark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simoncui/proj/epark/CMakeFiles /Users/simoncui/proj/epark//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simoncui/proj/epark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pkg

# Build rule for target.
pkg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pkg
.PHONY : pkg

# fast build rule for target.
pkg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pkg.dir/build.make CMakeFiles/pkg.dir/build
.PHONY : pkg/fast

#=============================================================================
# Target rules for targets named epark

# Build rule for target.
epark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 epark
.PHONY : epark

# fast build rule for target.
epark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/epark.dir/build.make CMakeFiles/epark.dir/build
.PHONY : epark/fast

cmd/main.o: cmd/main.cpp.o
.PHONY : cmd/main.o

# target to build an object file
cmd/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/epark.dir/build.make CMakeFiles/epark.dir/cmd/main.cpp.o
.PHONY : cmd/main.cpp.o

cmd/main.i: cmd/main.cpp.i
.PHONY : cmd/main.i

# target to preprocess a source file
cmd/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/epark.dir/build.make CMakeFiles/epark.dir/cmd/main.cpp.i
.PHONY : cmd/main.cpp.i

cmd/main.s: cmd/main.cpp.s
.PHONY : cmd/main.s

# target to generate assembly for a file
cmd/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/epark.dir/build.make CMakeFiles/epark.dir/cmd/main.cpp.s
.PHONY : cmd/main.cpp.s

pkg/hello.o: pkg/hello.cpp.o
.PHONY : pkg/hello.o

# target to build an object file
pkg/hello.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pkg.dir/build.make CMakeFiles/pkg.dir/pkg/hello.cpp.o
.PHONY : pkg/hello.cpp.o

pkg/hello.i: pkg/hello.cpp.i
.PHONY : pkg/hello.i

# target to preprocess a source file
pkg/hello.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pkg.dir/build.make CMakeFiles/pkg.dir/pkg/hello.cpp.i
.PHONY : pkg/hello.cpp.i

pkg/hello.s: pkg/hello.cpp.s
.PHONY : pkg/hello.s

# target to generate assembly for a file
pkg/hello.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pkg.dir/build.make CMakeFiles/pkg.dir/pkg/hello.cpp.s
.PHONY : pkg/hello.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... epark"
	@echo "... pkg"
	@echo "... cmd/main.o"
	@echo "... cmd/main.i"
	@echo "... cmd/main.s"
	@echo "... pkg/hello.o"
	@echo "... pkg/hello.i"
	@echo "... pkg/hello.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

